apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-hare
spec:
  selector:
    matchLabels:
      app: animals
  replicas: 2 
  template: 
    metadata:
      labels:
        app: animals
    spec:
      containers:
      - name: animals
        image: supergiantkir/animals:hare
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-bear
spec:
  selector:
    matchLabels:
      app: animals
  replicas: 1 
  template: 
    metadata:
      labels:
        app: animals
    spec:
      containers:
      - name: animals
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80

---
kind: Service      # Create new service
apiVersion: v1     
metadata:
  name: animals-service # Name of the service (DNS - RFC 2929)
spec:
  selector:
    app: animals
    # Run on any pod with label - app:myapp
  ports:          # Map incoming port to target port
  - name: animals-port    # Setting multiple ports listen 
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  
