---
kind: Service      # Create new service
apiVersion: v1     
metadata:
  name: animals-service # Name of the service (DNS - RFC 2929)
spec:
  selector:
    statefulset.kubernetes.io/pod-name: animals-hare-0
    # Run on any pod with label - app:myapp
  ports:          # Map incoming port to target port
  - name: animals-port    # Setting multiple ports listen 
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: animals-hare
spec:
  serviceName: "animals-service"
  selector:
    matchLabels:
      app: animals
  replicas: 1 
  template: 
    metadata:
      labels:
        app: animals
    spec:
      containers:
      - name: animals
        image: supergiantkir/animals:hare
        ports:
        - containerPort: 80

  
